name: Sandbox (Node)

on:
  workflow_dispatch:

jobs:
  node-sandbox-build:
    name: "🚀 Node Build Sandbox"
    uses: D2nke/my_workflows/.github/workflows/node_build.yml@feat/new_base
    secrets: inherit

  # node-sandbox-deploy:
  #   name: "🚀 Node Deploy to Sandbox"
  #   uses: D2nke/my_workflows/.github/workflows/node_sandbox_deploy.yml@feat/new_base
  #   secrets: inherit
